---
name: Update LOLBAS-Project-hegusung.github.io
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  workflow_run:
    workflows: ["PUSH & PULL REQUEST - YAML Lint and Schema Validation Checks"]
    types: [completed]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork == false && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Change .yml to .md
        run: |
          for x in $(find yml/ -name '*.yml'); do echo "---" >> "$x"; mv "$x" "${x/%\.yml/.md}"; done
          mv yml/OSBinaries yml/Binaries
          mv yml/OSLibraries yml/Libraries
          mv yml/OSScripts yml/Scripts
          rm -r yml/HonorableMentions

      - name: Deploy to LOLBAS-Project-hegusung.github.io repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: hegusung/LOLBAS-Project-hegusung.github.io
          publish_branch: master
          publish_dir: yml
          destination_dir: _lolbas
          enable_jekyll: true
          keep_files: false
          commit_message: "Applying update "
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
