---
name: PUSH - Update LOLBAS count
on: [push]

jobs:
  upload_lolbas_count:
    runs-on: ubuntu-latest
    steps:
      - name: checkout LOLBAS project
        uses: actions/checkout@v3

      - name: install python 3.10    
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: install dependencies
        run: poetry install --no-interaction 

      - name: run lolbas_count.py
        run: |
          poetry run python scripts/lolbas_count.py

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: upload new lolbas_count.svg to s3 bucket
        run: |
          aws s3 sync . s3://lolbas-project --exclude "*" --include "*.svg"
